/*
 * VFS Error codes
 * Last updated: 15-Nov-2012
 */
//New  (if the argument is not specified)
#define ERR_VFS_CREATE_00 "createvfs_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_CREATE_01 "createvfs_FAILURE DATA_FILE_ALREADY_EXISTS"
#define ERR_VFS_CREATE_02 "createvfs_FAILURE CANNOT_CREATE_DATAFILE"

 // The slash (/) character is not allowed
#define ERR_VFS_CREATE_03 "createvfs_FAILURE INVALID_CHARACTER_IN_NAME"
// Valid range for size is 1 to 1024 (inclusive)
#define ERR_VFS_CREATE_04 "createvfs_FAILURE INVALID_SIZE"
//New   (If label name exceeds 30 characters)
#define ERR_VFS_CREATE_05 "createvfs_FAILURE VFS_LABEL_TOO_LARGE"

#define ERR_VFS_MOUNT_00 "mountvfs_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_MOUNT_01 "mountvfs_FAILURE DATA_FILE_NOT_FOUND"
#define ERR_VFS_MOUNT_02 "mountvfs_FAILURE CANNOT_READ_FROM_FILE"
//New
#define ERR_VFS_MOUNT_03 "mountvfs_FAILURE VFS_ALREADY_MOUNTED"

#define ERR_VFS_UNMOUNT_00 "unmountvfs_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
// Use when fopen fails
#define ERR_VFS_UNMOUNT_01 "unmountvfs_FAILURE DATA_FILE_NOT_FOUND"
// Use when fwrite fails
#define ERR_VFS_UNMOUNT_02 "unmountvfs_FAILURE CANNOT_WRITE_TO_FILE"
//New
#define ERR_VFS_UNMOUNT_03 "unmountvfs_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_MAKEDIR_00 "makedir_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
//changed to FILESYSTEM_FULL from UNABLE_TO_CREATE_NEWDIR
#define ERR_VFS_MAKEDIR_01 "makedir_FAILURE FILESYSTEM_FULL"
#define ERR_VFS_MAKEDIR_02 "makedir_FAILURE INVALID_CHARACTER_IN_DIRNAME"
#define ERR_VFS_MAKEDIR_03 "makedir_FAILURE DIRECTORY_ALREADY_EXISTS"
//New
#define ERR_VFS_MAKEDIR_05 "makedir_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_DELETEDIR_00 "deletedir_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_DELETEDIR_01 "deletedir_FAILURE CANNOT_FIND_SPECIFIED_DIR"
#define ERR_VFS_DELETEDIR_02 "deletedir_FAILURE DIRECTORY_IS_NOT_EMPTY"
//New
#define ERR_VFS_DELETEDIR_04 "deletedir_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_MOVEDIR_00 "movedir_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_MOVEDIR_01 "movedir_FAILURE CANNOT_FIND_SPECIFIED_SOURCEDIR"
//(if specified dir is not there, it is not created in this case unlike in add dir)
#define ERR_VFS_MOVEDIR_02 "movedir_FAILURE CANNOT_FIND_SPECIFIED_DESTINATIONDIR"
//New
#define ERR_VFS_MOVEDIR_04 "movedir_FAILURE SOURCE_CANNOT_BE_FILE"
#define ERR_VFS_MOVEDIR_05 "movedir_FAILURE DESTINATION_ALREADY_HAVE_SOURCE_DIR"
//New
#define ERR_VFS_MOVEDIR_06 "movedir_FAILURE CANNOT_MOVE_PARENT_TO_CHILD_DIR"
//New
#define ERR_VFS_MOVEDIR_07 "movedir_FAILURE DESTINATION_CANNOT_BE_FILE"
//New
#define ERR_VFS_MOVEDIR_08 "movedir_FAILURE VFS_NOT_MOUNTED"

//New
#define ERR_VFS_LISTDIR_00 "listdir_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_LISTDIR_01 "listdir_FAILURE CANNOT_FIND_SPECIFIED_PATH_OR_DIR"
#define ERR_VFS_LISTDIR_02 "listdir_FAILURE INVALID_FLAG"
#define ERR_VFS_LISTDIR_03 "listdir_FAILURE VFS_NOT_MOUNTED"
#define ERR_VFS_LISTDIR_04 "listdir_FAILURE CANNOT_CREATE_OUTPUTFILE"

#define ERR_VFS_ADDFILE_00 "addfile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_ADDFILE_02 "addfile_FAILURE INVALID_CHARACTER_IN_FILENAME"
#define ERR_VFS_ADDFILE_03 "addfile_FAILURE FILE_ALREADY_EXISTS"
#define ERR_VFS_ADDFILE_04 "addfile_FAILURE FILE_SYSTEM_FULL"
//New
#define ERR_VFS_ADDFILE_05 "addfile_FAILURE CANNOT_WRITE_TO_DATAFILE"
//New : (if data exceeds block size)
#define ERR_VFS_ADDFILE_06 "addfile_FAILURE FILE_TOO_LARGE"
//New
#define ERR_VFS_ADDFILE_07 "addfile_FAILURE VFS_NOT_MOUNTED"
#define ERR_VFS_ADDFILE_08 "addfile_FAILURE SOURCE_FILE_NOT_FOUND"

#define ERR_VFS_LISTFILE_00 "listfile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_LISTFILE_01 "listfile_FAILURE SOURCE_FILE_PATH_NOT_FOUND"
#define ERR_VFS_LISTFILE_02 "listfile_FAILURE NOT_A_TEXT_FILE"
//New
#define ERR_VFS_LISTFILE_03 "listfile_FAILURE CANNOT_CREATE_OUTPUTFILE"
//New
#define ERR_VFS_LISTFILE_04 "listfile_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_UPDATEFILE_00 "updatefile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_UPDATEFILE_01 "updatefile_FAILURE INTERNAL_FILE_NOT_FOUND"
#define ERR_VFS_UPDATEFILE_02 "updatefile_FAILURE EXTERNAL_FILE_NOT_FOUND"
//New
#define ERR_VFS_UPDATEFILE_03 "updatefile_FAILURE EXTERNAL_FILE_TOO_LARGE"
//New
#define ERR_VFS_UPDATEFILE_04 "updatefile_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_REMOVEFILE_00 "removefile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
// Use this error even when the given argument is a directory and not a file
#define ERR_VFS_REMOVEFILE_01 "removefile_FAILURE CANNOT_FIND_SPECIFIED_FILE"
//New
#define ERR_VFS_REMOVEFILE_02 "removefile_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_MOVEFILE_00 "movefile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_MOVEFILE_01 "movefile_FAILURE CANNOT_FIND_SOURCEFILE"
#define ERR_VFS_MOVEFILE_02 "movefile_FAILURE CANNOT_FIND_DESTINATION_PATH"
//New
#define ERR_VFS_MOVEFILE_06 "movefile_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_COPYFILE_00 "copyfile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_COPYFILE_01 "copyfile_FAILURE CANNOT_FIND_SOURCEFILE"
#define ERR_VFS_COPYFILE_02 "copyfile_FAILURE CANNOT_FIND_DESTINATIONPATH"
#define ERR_VFS_COPYFILE_03 "copyfile_FAILURE CANNOT_COPY_DIR_TO_FILE"
#define ERR_VFS_COPYFILE_04 "copyfile_FAILURE FILE_SYSTEM_FULL"
#define ERR_VFS_COPYFILE_05 "copyfile_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_EXPORTFILE_00 "exportfile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
#define ERR_VFS_EXPORTFILE_01 "exportfile_FAILURE CANNOT_FIND_SOURCEFILE"
#define ERR_VFS_EXPORTFILE_02 "exportfile_FAILURE CANNOT_CREATE_OUTPUTFILE"
#define ERR_VFS_EXPORTFILE_03 "exportfile_FAILURE CANNOT_EXPORT_DIR"
//New
#define ERR_VFS_EXPORTFILE_04 "exportfile_FAILURE VFS_NOT_MOUNTED"

#define ERR_VFS_SEARCHFILE_00 "searchfile_FAILURE VFS_INSUFFICIENT_ARGUMENTS"
//New
#define ERR_VFS_SEARCHFILE_02 "searchfile_FAILURE VFS_NOT_MOUNTED"
